# Generated by Django 3.2.8 on 2021-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('clientid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bankbalance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sendername', models.CharField(max_length=20)),
                ('receivername', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
